import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const CONTRIBUTORS_PATH = resolve(import.meta.dirname!, '..', 'CONTRIBUTORS.md');
const DELIMITER_START = '<!-- This file is auto-generated by .github/workflows/contributors.yml -->\n<!-- Do not edit manually — changes will be overwritten -->\n';

interface Contributor {
  name: string;
  login: string;
  contributions: number;
}

function parseTable(content: string): Contributor[] {
  const lines = content.split('\n');
  const contributors: Contributor[] = [];
  let inTable = false;

  for (const line of lines) {
    if (line.startsWith('| Contributor |')) continue; // header
    if (line.startsWith('|---')) {
      inTable = true;
      continue;
    }
    if (!inTable || !line.startsWith('|')) continue;

    const cells = line.split('|').map(s => s.trim()).filter(Boolean);
    if (cells.length >= 3) {
      const name = cells[0];
      const linkMatch = cells[1].match(/\[(.+?)\]\(/);
      const login = linkMatch ? linkMatch[1] : cells[1];
      const contributions = parseInt(cells[2], 10) || 0;

      // Validate it's a real row (not a stray pipe character)
      if (login) {
        contributors.push({ name, login, contributions });
      }
    }
  }

  return contributors;
}

function formatTable(contributors: Contributor[]): string {
  if (contributors.length === 0) {
    return `${DELIMITER_START}| Contributor | GitHub | Contributions |
|-------------|--------|---------------|
`;
  }

  let out = DELIMITER_START;
  out += '| Contributor | GitHub | Contributions |\n';
  out += '|-------------|--------|---------------|\n';

  for (const c of contributors) {
    out += `| ${c.name} | [${c.login}](https://github.com/${c.login}) | ${c.contributions} |\n`;
  }

  return out;
}

const author = process.env.PR_AUTHOR;
if (!author) {
  console.log('No PR_AUTHOR env var set — skipping');
  process.exit(0);
}

let content: string;
try {
  content = readFileSync(CONTRIBUTORS_PATH, 'utf-8');
} catch {
  // File doesn't exist yet — create from seed
  writeFileSync(CONTRIBUTORS_PATH, formatTable([]));
  content = readFileSync(CONTRIBUTORS_PATH, 'utf-8');
}

const contributors = parseTable(content);
const existing = contributors.find(
  c => c.login.toLowerCase() === author.toLowerCase()
);

if (existing) {
  existing.contributions += 1;
  console.log(`Updated: ${author} now has ${existing.contributions} contributions`);
} else {
  contributors.push({ name: author, login: author, contributions: 1 });
  console.log(`Added new contributor: ${author}`);
}

// Sort by contributions descending
contributors.sort((a, b) => b.contributions - a.contributions);

writeFileSync(CONTRIBUTORS_PATH, formatTable(contributors));
